language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - py.test tests
  - py.test --cov=bin

after_success:
- codecov