version: '3.2'
services:
    store:
        image: redis
        networks:
            - backend
    db:
        image: postgres
        networks:
            - backend
    worker:
        build: worker
        networks:
            - backend
        volumes:
            - cctf:/cctf
            - type: bind
              source: ./pack
              target: /pack
        depends_on:
            - store
            - db
        environment:
            - REDIS_HOST=store
            - POSTGRES_HOST=db
    web:
        build: web
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - cctf:/cctf
            - type: bind
              source: ./pack
              target: /pack
        depends_on:
            - store
            - db
        environment:
            - REDIS_HOST=store
            - POSTGRES_HOST=db
networks:
    backend:

volumes:
    cctf:
