version: '3'
services:
    store:
        image: redis
        networks:
            - backend
    db:
        image: mongo
        networks:
            - backend
    postgres:
        image: postgres
        networks:
            - backend
    worker:
        build: worker
        networks:
            - backend
        volumes:
            - cctf:/cctf
        depends_on:
            - store
            - db
            - postgres
        environment:
            - REDIS_HOST=store
            - MONGO_HOST=db
            - POSTGRES_HOST=postgres
    web:
        build: web
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - cctf:/cctf
        depends_on:
            - store
            - db
            - postgres
        environment:
            - REDIS_HOST=store
            - MONGO_HOST=db
            - POSTGRES_HOST=postgres
            - RESET=1
            - ENVIRONMENT=dev
networks:
    backend:

volumes:
    cctf:
