version: '3.2'
services:
    store:
        image: redis
        networks:
            - backend
    db:
        image: postgres
        networks:
            - backend
    pgadmin:
        image: dpage/pgadmin4
        networks:
            - backend
        ports:
            - "8000:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=swift106@d.umn.edu
            - PGADMIN_DEFAULT_PASSWORD=password
    worker:
        build: worker
        networks:
            - backend
        volumes:
            - cctf:/cctf
            - type: bind
              source: ./pack
              target: /pack
        depends_on:
            - store
            - db
        environment:
            - REDIS_HOST=store
            - POSTGRES_HOST=db
    web:
        build: web
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - cctf:/cctf
            - type: bind
              source: ./pack
              target: /pack
        depends_on:
            - store
            - db
        environment:
            - REDIS_HOST=store
            - POSTGRES_HOST=db
            - RESET=1
            - ENVIRONMENT=dev
            - ADMIN_USER_EMAIL=swift106@d.umn.edu
            - ADMIN_USER_PASSWORD=password
networks:
    backend:

volumes:
    cctf:
